# Generated by Django 5.1 on 2024-09-07 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_donations"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="conservationOrganization",
            new_name="ConservationOrganizations",
        ),
    ]
