# Generated by Django 5.1 on 2024-09-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_rename_conservationorganization_conservationorganizations"),
    ]

    operations = [
        migrations.AddField(
            model_name="conservationorganizations",
            name="date_of_creation",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
