# Generated by Django 5.1 on 2024-09-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_conservationorganizations_date_of_creation"),
    ]

    operations = [
        migrations.CreateModel(
            name="MyModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "postGreDb",
            },
        ),
    ]
