# Generated by Django 5.1 on 2024-09-08 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_mymodel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MyModel",
        ),
    ]
