# Generated by Django 5.1 on 2024-09-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_delete_mymodel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ConservationOrganizations",
        ),
        migrations.AddField(
            model_name="conservationinitiatives",
            name="date_of_creation",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="conservationinitiatives",
            name="mission",
            field=models.TextField(blank=True),
        ),
    ]
