# Generated by Django 5.1 on 2024-09-08 21:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_delete_conservationorganizations_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conservationinitiatives",
            name="current_funds",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="conservationinitiatives",
            name="email",
            field=models.EmailField(
                blank=True,
                default="example@gmai.com",
                max_length=254,
                validators=[django.core.validators.EmailValidator()],
            ),
        ),
        migrations.AddField(
            model_name="conservationinitiatives",
            name="number_of_donors",
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="conservationinitiatives",
            name="target_fund_raise",
            field=models.FloatField(blank=True, default=0),
        ),
    ]
