# Generated by Django 5.1 on 2024-09-08 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_conservationinitiatives_current_funds_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conservationinitiatives",
            name="images",
            field=models.ImageField(
                blank=True, storage="conservation_projects/", upload_to=""
            ),
        ),
    ]
