# Generated by Django 5.1 on 2024-09-09 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_conservationinitiatives_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conservationinitiatives",
            name="images",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
