# Generated by Django 5.1 on 2024-09-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_alter_conservationinitiatives_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="donations",
            name="donation_amount",
            field=models.FloatField(default=0),
        ),
    ]
