# Generated by Django 5.1 on 2024-09-09 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_artist"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArtWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("creation_date", models.DateField(blank=True, null=True)),
                (
                    "donation_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "artwork_image",
                    models.ImageField(blank=True, null=True, upload_to="works/"),
                ),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="works",
                        to="api.artist",
                    ),
                ),
            ],
        ),
    ]
