# Generated by Django 5.1 on 2024-09-10 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_artwork"),
    ]

    operations = [
        migrations.AlterField(
            model_name="educationarticle",
            name="author",
            field=models.TextField(blank=True),
        ),
    ]
