# Generated by Django 5.1 on 2024-09-10 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_alter_educationarticle_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="educationarticle",
            name="slug",
            field=models.SlugField(editable=False, max_length=255, unique=True),
        ),
    ]
