# Generated by Django 5.1 on 2024-09-26 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_carboncredit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carboncredit",
            name="user",
        ),
    ]
